spring:
  application:
    name: springboot-artificial-intelligence-milvus
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
  vectorstore:
    milvus:
      client:
        host: "localhost"
        port: 19530
        username: "root111111"
        password: "milvus11111"
      databaseName: "default"
      collectionName: "vector_store"
      embeddingDimension: 1536
      indexType: IVF_FLAT
      metricType: COSINE
rag:
  aiapp:
    documentsToLoad:
      # Samsung Galaxy s24
      - https://www.gsmarena.com/samsung_galaxy_s24-12773.php